//! GENERATED by org/tools/work-tools/color-dna from palette.json — do not edit; run `color-dna apply`.

use ratatui::style::{Color, Modifier};

use super::tokyonight::Theme;

const fn rgb(r: u8, g: u8, b: u8) -> Color {
    Color::Rgb(r, g, b)
}

impl Theme {
    pub const fn color_dna() -> Self {
        Self {
            bg_base: rgb(20, 20, 20),
            bg_light: rgb(28, 28, 28),
            bg_dark: rgb(28, 28, 28),
            bg_highlight: rgb(22, 22, 22),
            bg_hover: rgb(22, 22, 22),
            bg_terminal: rgb(10, 10, 10),
            accent_user: rgb(216, 216, 216),
            accent_assistant: rgb(176, 132, 235),
            accent_thinking: rgb(106, 106, 106),
            accent_tool: rgb(78, 201, 176),
            accent_system: rgb(86, 212, 221),
            accent_error: rgb(229, 72, 77),
            accent_success: rgb(61, 214, 140),
            accent_running: rgb(86, 156, 214),
            accent_skill: rgb(86, 156, 214),
            text_primary: rgb(216, 216, 216),
            text_secondary: rgb(180, 180, 180),
            gray_dim: rgb(74, 74, 74),
            gray: rgb(106, 106, 106),
            gray_bright: rgb(106, 106, 106),
            command: rgb(61, 214, 140),
            path: rgb(61, 214, 140),
            running: rgb(86, 156, 214),
            warning: rgb(230, 92, 76),
            fuzzy_accent: rgb(86, 156, 214),
            accent_plan: rgb(86, 212, 221),
            accent_verify: rgb(176, 132, 235),
            accent_remember: rgb(61, 214, 140),
            selection_border: rgb(86, 156, 214),
            hover_border: rgb(42, 42, 42),
            prompt_border: rgb(58, 58, 58),
            prompt_border_active: rgb(86, 156, 214),
            accent_model: rgb(78, 201, 176),
            scrollbar_bg: rgb(20, 20, 20),
            scrollbar_fg: rgb(58, 58, 58),
            diff_delete_bg: rgb(45, 21, 22),
            diff_delete_fg: rgb(229, 104, 109),
            diff_insert_bg: rgb(18, 39, 26),
            diff_insert_fg: rgb(79, 214, 140),
            diff_equal_fg: rgb(106, 106, 106),
            diff_gutter_fg: rgb(58, 58, 58),
            bg_visual: rgb(38, 79, 120),
            paste_bg: rgb(20, 20, 20),
            paste_fg: rgb(216, 216, 216),
            paste_dim: rgb(106, 106, 106),
            md_heading_h1: rgb(176, 132, 235),
            md_heading_h1_mod: Modifier::BOLD,
            md_heading_h2: rgb(176, 132, 235),
            md_heading_h2_mod: Modifier::BOLD,
            md_heading_h3: rgb(176, 132, 235),
            md_heading_h3_mod: Modifier::BOLD,
            md_heading_h4: rgb(176, 132, 235),
            md_heading_h4_mod: Modifier::BOLD,
            md_heading_h5: rgb(176, 132, 235),
            md_heading_h5_mod: Modifier::BOLD,
            md_heading_h6: rgb(176, 132, 235),
            md_heading_h6_mod: Modifier::BOLD,
            md_code: rgb(61, 214, 140),
            md_task_checked: rgb(61, 214, 140),
            md_task_unchecked: rgb(106, 106, 106),
            md_muted: rgb(106, 106, 106),
            md_code_bg: rgb(28, 28, 28),
            md_text: rgb(180, 180, 180),
            link_fg: rgb(86, 156, 214),
        }
    }
}
